### PR TITLE
remove token from frontend

### LINKED ISSUE #149: Operation after logout
**Describe the bug**
> 如果你登出之後再按上一頁，網頁會因為cache讓你可以看到之前的頁面，但這時候理論上應該不能對後端做操作就是了
-- @NOOBDY 

**To Reproduce**
1. login
2. go to an authorization-required page
3. logout
4. 返回上一頁
5. still able to operate the page

**Expected behavior**
Should not be able to operate the page after logout

### PR DESCRIPTION
**Pull request by x06lan**
Ex. Resolves #149 

### Changes

- force clear token in frontend when logout

### Testing Approach (if unconventional)

1. login
2. go to an authorization-required page
3. logout
4. 返回上一頁
5. should be back to login page

### CODE REVIEW

**Comment by NOOBDY** [comment]
this is the same fix in #158

**Review by Error0229 — APPROVED** [review]
WOMM

**Comment by Error0229** [comment]
I don't need to go to an authorization-required page, the logout function still works too.

**Review by NOOBDY — APPROVED** [review]
If it works it works

**Pull request merged**
