### PR TITLE
[frontend] Info pages api

### LINKED ISSUE #94: [frontend] Calling API
## U know rule and so do i
✔️: done and merged
⌛: pr and waiting for review
❌: not finished

### (A) Discover & News TYK ✔️
- [x] /news/newsID
- [x] /discover?pageNumber={pageNumber}

### (B) ViewShop TYK ⌛
- [x] /sellerID/shop
- [x] /seller/manageProducts
- [x] /seller/manageProducts/new
- [x] /seller/manageProducts/productID

### (C) Order TYK ⌛
- [x] /buyer/order
- [x] /buyer/order/orderID
- [x] /seller/order/orderID
- [x] /seller/order

### (D) Product TYK ⌛
- [x] /product

### (E) Coupon UG ⌛
- [x] /admin/manageCoupon
- [x] /admin/manageCoupon/couponID
- [x] /admin/manageCoupon/new
- [x] /seller/manageCoupon
- [x] /seller/manageCoupon/new
- [x] /seller/manageCoupon/couponID
- [x] /sellerCoupon

### (F) Report TYK ✔️
- [x] /seller/report
- [x] /seller/report/reportID
- [x] /admin/report
- [x] /admin/report/reportID

### (G) Cart UG ❌
- [x] /buyer/cart 

### (H) Login & Signup UG ✔️
- [x] /login
- [x] /signup

### (I) Info Settings UG ✔️
- [x] /user/info
- [x] /seller/info

### (J) Admin ManageUser UG ⌛
- [x] /admin/manageUser 

### (K) Security UG ✔️
- [x] /user/security
- [x] /user/security/password
- [x] /user/security/manageCreditCard
- [x] /user/security/manageCreditCard/new

### (L) Search TYK ⌛
- [x] /search
- [-] /search?shop={keyword}
- [x] /search?keyword={keyword}

### PR DESCRIPTION
**Pull request by UGisBusy**
Resolves #94 

#### Page
- [x] [/user/info](http://localhost:8080/user/info)
- [x] [/seller/info](http://localhost:8080/user/seller/info)

#### APIs
- User Get Info
- User Edit Info
- Seller get shop info
- Seller edit shop info

#### Function
- when navigate to both pages, fetch the data from backend (image might take longer to load)
- when press ``save`` in both pages, itll send data to backend.
  - the image must be any kind of image file
  - will pop up alart to inform the result

### Testing Approach (if unconventional)
```sh
docker compose up --build
```
- go to the two pages
- send something

### Additional context
N/A

### CODE REVIEW

**Review by x06lan — DISMISSED** [review]

**Review by NOOBDY — CHANGES_REQUESTED** [review]
Resolve conflict w/ `main`

**Comment by KatoToyoki** [comment]
image
the text fields are fine in both seller and buyer but the image will not be updated after i select new .jpeg, .jpg or .png file (not alerted as well) after i click save. 

i've test on firefox, safari and edge, all with broken image

is it the proper behavior?

**Comment by UGisBusy** [comment]
this might cause by .env.
if u r hosting using go run, pls check the fallow field of ur .dev.env
```
MINIO_HOST=localhost
MINIO_PRESIGNED_URL_HOST=localhost:9000
```
if u r hosting with docker or the bug still replicatble after with env variable set like above, pls provide some log.

**Comment by KatoToyoki** [comment]
after source `.dev.env`, i still can't get the image on web page
in minIO, the images are stored but it just not reveal on the webpage i don't know why

**Review by nonorze-VOXX — APPROVED** [review]
image

**Review by NOOBDY — APPROVED** [review]

**Review by KatoToyoki — APPROVED** [review]

**Pull request merged**
