### PR TITLE
Create LICENSE

### LINKED ISSUE #28: Forgor LICENSE 💀
We didn't have a LICENSE file

### PR DESCRIPTION
**Pull request by NOOBDY**
Fix #28

### CODE REVIEW

**Review by kryr34 — APPROVED** [review]
This PR must be everyone approved. Read [this](https://choosealicense.com/licenses/gpl-3.0/) to understand your rights.

**Review by UGisBusy — APPROVED** [review]
LGTM

**Review by Error0229 — APPROVED** [review]
LGTM

**Review by x06lan — APPROVED** [review]

**Review by KatoToyoki — APPROVED** [review]
lgtm

**Pull request merged**
