### PR TITLE
[DevOps] Setup deploy environement w/ Docker & docker-compose

### LINKED ISSUE #6: Setup deploy environment
Setup builder with Dockerfile and container connections with docker compose

### PR DESCRIPTION
**Pull request by NOOBDY**
Please test on your machines, not sure if docker works correctly on all three platforms (although it would finally be deployed on a Linux machine)

### CODE REVIEW

**Comment by NOOBDY** [comment]
Things to check:
* go to `localhost:8080` with any browser to see if vite + react template webpage works
* go to `localhost:8080/api/hello` with curl or browser and see if it replies 
```json
{
  "message": "ok"
}
```
* try to connect to postgres with `docker exec -it twp-postgres-1 psql -U root -d db`
* go to minio web console by going to `localhost:9090` and try to login with default config

**Review by Error0229 — APPROVED** [review]
Works fine on WSL2 Ubuntu-20.04 and checked

**Comment by KatoToyoki** [comment]
4 things are all checked and works fine on mac.

**Review by KatoToyoki — APPROVED** [review]
4 things are all checked and works fine on mac.

**Comment by UGisBusy** [comment]
Worked on both windows and wsl ubuntu 22.04 after updating / installing docker and go.

**Review by UGisBusy — APPROVED** [review]
Worked on both windows and wsl ubuntu 22.04 after updating / installing docker and go.
(Changed to a review)

**Pull request merged**
